version: "3"

services:
    sshca:
     build: "./sshca"
     ports:
      - "2223:22"
     networks:
      - sshca-net

    server1:
     build: "./server1"
     ports:
      - "2222:22"
     networks:
      - sshca-net

    client1:
     build: "./client1"
     networks:
      - sshca-net

networks:
    sshca-net:
